// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SupplierHunterEntities
{
    public partial class ProductSupplier
    {
        public int IdProductSupplier { get; set; }
        public int RidProduct { get; set; }
        public int RidSupplier { get; set; }
        public int Availability { get; set; }
        public int MinShippingDays { get; set; }
        public int? RidDiscount { get; set; }
        public decimal UnitPrice { get; set; }

        public virtual Discount RidDiscountNavigation { get; set; }
        public virtual Product RidProductNavigation { get; set; }
        public virtual Supplier RidSupplierNavigation { get; set; }
    }
}