// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SupplierHunterEntities
{
    public partial class Season
    {
        public Season()
        {
            Discount = new HashSet<Discount>();
        }

        public int IdSeason { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Discount> Discount { get; set; }
    }
}