// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SupplierHunterEntities
{
    public partial class Supplier
    {
        public Supplier()
        {
            ProductSupplier = new HashSet<ProductSupplier>();
        }

        public int IdSupplier { get; set; }
        public string BusinessName { get; set; }
        public string Address { get; set; }

        public virtual ICollection<ProductSupplier> ProductSupplier { get; set; }
    }
}